server:
  port: 8181
spring:
  profiles:
    active:
      - dev
  application:
    name: smss_middle_app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gpsdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: gps_user
    password: gps_user
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT js
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.static.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456

mybatis:
  #entity扫描的包名
  type-aliases-package: cn.gov.bjtzh.smss.middle.entity.po
  #Mapper.xml所在的位置
  mapper-locations: classpath:cn/gov/bjtzh/smss/middle/entity/mapper/*Mapper.xml
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  identity: mysql
  not-empty: true
jwt:
  expiration: 86400
  header: SMSS-Authorization
  jackson:
    serialization:
      INDENT_OUTPUT: true
  secret: smssSecret
  tokenHead: SmssHead
logging:
  level:
    cn:
      gov:
        bjtzh:
          smss:
            middle:
              entity:
                dao: debug